[environment]
scripts = ./scripts
job_dir = ./jobs
admin_name = admin

[iaas]
providers = [linode, ucloud]

  [iaas.linode]
  token = ___
  docker_mirror = https://docker.io
  # docker mirror alternatives: https://hub-mirror.c.163.com
  docker_image = ga6840/linode-cli:latest

    [iaas.linode.config_1]
    region = ap-southeast
    specs = 'g6-nanode-1'
    distro = linode/debian10
    ssh_port = 8921
    password = ___

  [iaas.ucloud]
  pubkey = ___ 
  prikey = ___
  docker_mirror = https://uhub.service.ucloud.cn
  docker_image = ga6840/ucloud-cli:latest
  username = ___
  password = ___

    [iaas.ucloud.config_1]
    region = cn-gd
    specs = 1cpu-1gb-1mb
    distro = 'Debian_9'
    ssh_port = 22
    password = ___

[service]
max_restart = 3

  [service.calabash]
  mesh_replicas = 1
  mesh_sharding = 1

  network = bridge
  portmap = 80:8964

  # See https://docs.docker.com/engine/reference/commandline/service_create
  constraints = [
    'node.role==manager'
  ]

  docker_image = ga6840/calabash
  configs = [
    'calabash_config:/code/calabash/config.toml'
  ]
  mounts = [
    'src=/var/run/docker.sock,dst=/var/run/docker.sock',
		'src=/tmp,dst=/mnt/test,ro=true',
  ]
  docker_exec = node ./jobd/jobd.js --config ./config.toml | tee -a /var/log/calabash.log
