[docker-pull]
exec = [
  source $script/iaas/linode.sh $linode_token,
  $DOCKER pull ga6840/linode-cli:lastest
]
if_not = docker image inspect linode-cli

[list-nodes]
verbose = false
exec = [
  source $scripts/iaas/linode.sh $linode_token,
  list_nodes
]
dep = linode:docker-pull

[list-nodetypes]
exec = [
  source $scripts/iaas/linode.sh $linode_token,
  list_node_types
]
dep = linode:docker-pull
