[source]
verbose = false
source = . $scripts/iaas/linode.sh $linode_token $linode_docker_mirror

[list-nodes]
exec = linode_node_list
dep = linode:source

[delete-node]
exec = [
  check_args nodeid
  linode_node_delete $nodeid
]
dep = linode:source

[account-balance]
exec = linode_account_balance
dep = linode:source

