[source]
verbose = false
source = [
  . $scripts/common.env.sh,
  '. $scripts/iaas/linode.sh `unpack \$iaas_linode_{token,docker_mirror}`'
]

[list-nodes]
exec = linode_node_list
dep = linode:source

[delete-node]
exec = [
  check_args nodeid
  linode_node_delete $nodeid
]
dep = linode:source

[account-balance]
exec = linode_account_balance
dep = linode:source
