[source]
verbose = false
source = . $scripts/iaas/all.sh

[list-nodes]
exec = [
  'format=${format-table}',
  '[ $format == table ] && linode_node_list || linode_node_list_in_json'
]
dep = linode:source

[delete-node]
exec = [
  require_args nodeid,
  linode_node_delete $nodeid
]
dep = linode:source

[account-balance]
exec = linode_account_balance
dep = linode:source
