[allocate]
source = [
  . $scripts/common.env.sh,
  . $scripts/iaas/all.sh,
  . $scripts/random/random.sh
]
spawn = pty
exec = [
  require_args iaascfg,
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read region specs distro passwd <<< $(unpack \$iaas_${iaascfg}_{region,specs,distro,password})',
  'node_label=calabash-${cbuser-$admin_name}-$(rname_short)',
  '${provider}_node_create $passwd $node_label $region $specs $distro',
  export node_label
]

[install]
source = [
  . $scripts/iaas/all.sh,
  . $scripts/ssh/ssh.sh,
  . $scripts/swarm/swarm.sh,
]
spawn = pty
user = root # for ssh-copy-id to find identity file.
exec = [
  require_args iaascfg node_label,
  # unpack parameters
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read passwd port <<< $(unpack \$iaas_${iaascfg}_{password,ssh_port})',
  'read docker_mirror <<< $(unpack \$iaas_${provider}_docker_mirror)',
  # get node ID and IP
  'nodeID=`${provider}_node_filter_by_label $node_label`',
  'nodeIP=`${provider}_node_map_ipaddr $nodeID`',
  # refresh local known host list
  ssh-keygen -R $nodeIP,
  # allow ssh login from this host and from remote itself
  '$scripts/ssh/ssh-copy-id.expect root@$nodeIP $passwd',
  sshd_allow_self_login $nodeIP 22
  # change remote sshd port
  sshd_change_port root@$nodeIP 22 $port,
  # install docker engine
  swarm_install root@$nodeIP $port $iaascfg $docker_mirror,
  # export node IP address
  export nodeIP
]
dep = swarm:allocate

[bootstrap]
source = . $scripts/swarm/swarm.sh
exec = [
  require_args iaascfg nodeIP,
  # unpack parameters
  'read port <<< $(unpack \$iaas_${iaascfg}_ssh_port)',

  # initialize docker warm for the first time
  $SSH -p $port root@$nodeIP $DOCKER swarm init,

  # set label for this root swarm manager
  'swarm_node_label root@$nodeIP $port iaascfg=$iaascfg',
  'swarm_node_label root@$nodeIP $port shard=1',

  # upload config file as docker swarm secret/config
  swarm_update_secret_file root@$nodeIP $port calabash_config $_config_file_,

  # setup the first service
  swarm_service_deploy $nodeIP $port calabash,

  # finally, print node IP
  "echo Bootstrap node: $nodeIP"
]
dep = swarm:install

[expand]
source = . $scripts/swarm/swarm.sh
exec = [
  require_args iaascfg nodeIP role,
  # unpack parameters
  'read port <<< $(unpack \$iaas_${iaascfg}_ssh_port)',
  # join the swarm
  'joinCommand=`docker swarm join-token $role | grep token`',
  $SSH -p $port root@$nodeIP $DOCKER $joinCommand,
  # set label for this new swarm node
  'swarm_node_label root@$nodeIP $port iaascfg=$iaascfg',
  'swarm_node_label root@$nodeIP $port shard=${shard-1}',
]
dep = swarm:install
