[allocate]
source = [
  . $scripts/iaas/all.sh,
  . $scripts/random/random.sh
]
spawn = pty
exec = [
  require_args iaascfg,
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read region specs distro passwd <<< $(unpack \$iaas_${iaascfg}_{region,specs,distro,password})',
  'node_label=calabash-${cbuser-$admin_name}-$(rname_short)',
  '${provider}_node_create $passwd $node_label $region $specs $distro',
  export node_label
]

[install]
source = [
  . $scripts/iaas/all.sh,
  . $scripts/ssh/ssh.sh,
  . $scripts/swarm/swarm.sh
]
spawn = pty
user = root # for ssh-copy-id to find identity file.
exec = [
  require_args iaascfg node_label, # pass typeIP=private for private connection
  # unpack parameters
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read passwd port <<< $(unpack \$iaas_${iaascfg}_{password,ssh_port})',
  'read docker_mirror <<< $(unpack \$iaas_${provider}_docker_mirror)',
  # get node ID and IP
  'nodeID=`${provider}_node_filter_by_label $node_label`',
  'nodeIP=`${provider}_node_map_ipaddr $nodeID ${typeIP-public}`',
  # refresh local known host list
  ssh-keygen -R $nodeIP,
  # allow ssh login from this host to new remote peer
  'set -x',
  '$scripts/ssh/ssh-copy-id.expect root@$nodeIP $passwd',
  'set +x',
  # change remote sshd port
  sshd_change_port root@$nodeIP 22 $port,
  # install docker engine
  'swarm_install root@$nodeIP $port $iaascfg $docker_mirror ${node_label}-host',
  # export node IP address
  export nodeIP
]
dep = swarm:allocate

[bootstrap]
source = . $scripts/swarm/swarm.sh
exec = [
  require_args iaascfg nodeIP,
  # unpack parameters
  'read port <<< $(unpack \$iaas_${iaascfg}_ssh_port)',

  # initialize docker warm for the first time
  $SSH -p $port root@$nodeIP $DOCKER swarm init,

  # set label for this root swarm manager
  'swarm_node_label_bootstrap root@$nodeIP $port iaascfg=$iaascfg',
  'swarm_node_label_bootstrap root@$nodeIP $port shard=1',

  # upload config file as docker swarm secret/config
  swarm_update_secret_file root@$nodeIP $port calabash_config $_config_file_,

  # setup the first service
  swarm_service_create $nodeIP $port calabash,

  # finally, print node IP
  "echo Bootstrap node: $nodeIP"
]
dep = swarm:install

[expand]
source = . $scripts/swarm/swarm.sh
exec = [
  require_args iaascfg nodeIP role, # pass `shard=n' for naming shard
  # unpack parameters
  'read port <<< $(unpack \$iaas_${iaascfg}_ssh_port)',
  # join the swarm
  'joinCommand=`$DOCKER swarm join-token $role | grep token`',
  $SSH -p $port root@$nodeIP $joinCommand,
  # set label for this new swarm node
  'swarmNodeID=`swarm_node_id root@$nodeIP $port`',
  'swarm_node_label $swarmNodeID iaascfg=$iaascfg',
  'swarm_node_label $swarmNodeID shard=${shard-1}',
]
dep = swarm:install

[list-nodes]
source = . $scripts/swarm/swarm.sh
if = is_swarm_manager
exec = swarm_print_nodes

[list-services]
source = . $scripts/swarm/swarm.sh
if = is_swarm_manager
exec = swarm_print_services

[service-update]
source = . $scripts/swarm/swarm.sh
exec = [
  require_args serviceid, # pass `tag=v123' for update version
  swarm_service_update $serviceid $tag
]
