[hostname]
exec = hostname

[allocate]
source = [
  . $scripts/common.env.sh,
  . $scripts/iaas/all.sh,
  . $scripts/random/random.sh
]
spawn = pty
exec = [
  check_args iaascfg,
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read region specs distro passwd <<< $(unpack \$iaas_${iaascfg}_{region,specs,distro,password})',
  'node_label=calabash-$(rname_short)',
  '${provider}_node_create $passwd $node_label $region $specs $distro',
  export node_label
]

[install]
source = [
  . $scripts/iaas/all.sh,
  . $scripts/ssh/ssh.sh,
  . $scripts/swarm/swarm.sh,
]
spawn = pty
user = root # for ssh-copy-id to find identity file.
exec = [
  check_args iaascfg node_label,
  # unpack parameters
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read passwd port <<< $(unpack \$iaas_${iaascfg}_{password,ssh_port})',
  # get node ID and IP
  'nodeID=`${provider}_node_filter_by_label $node_label`',
  'nodeIP=`${provider}_node_map_ipaddr $nodeID`',
  # install ssh key, setup ssh port, and install docker-engine.
  ssh-keygen -R $nodeIP,
  '$scripts/ssh/ssh-copy-id.expect root@$nodeIP $passwd',
  sshd_change_port root@$nodeIP 22 $port,
  swarm_install root@$nodeIP $port $iaascfg
  # export/return node IP address
  export nodeIP
]
dep = swarm:allocate

[bootstrap]
source = . $scripts/swarm/swarm.sh
#verbose = true
exec = [
  check_args iaascfg nodeIP,
  # unpack parameters
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read passwd port <<< $(unpack \$iaas_${iaascfg}_{password,ssh_port})',
  'read docker_mirror <<< $(unpack \$iaas_${provider}_docker_mirror)',
  #initialize docker warm for the first time
  $SSH -p $port root@$nodeIP $DOCKER swarm init,
  'swarm_node_label root@$nodeIP $port iaas=$provider',
  # upload config file as docker swarm secret/config
  swarm_update_secret_file root@$nodeIP $port $swarm_config_key $_config_file_,
  # unpack service parameters
  '''
  read srv_name portmap docker_img docker_exec <<< \
  $(unpack \$swarm_service_bootstrap_{name,portmap,docker_image,docker_exec})
  ''',
  'version=`swarm_config_get root@$nodeIP $port ${swarm_config_key}.latest`',
  'command=`echo $docker_exec | sed -e "s/{{version}}/${version}/g"`',
  # now create the first swarm service
  '$SSH -p $port root@$nodeIP $DOCKER service rm ${srv_name}',
  '''
  set -x
  $SSH -p $port root@$nodeIP \
  $DOCKER service create --name ${srv_name} \
  --publish published=${portmap},target=${jobd_port} \
  --hostname="{{.Service.Name}}-{{.Task.Slot}}" \
  --secret ${swarm_config_key}.${version} \
  ${docker_mirror}${docker_img} ${command}
  set +x
  '''
]
dep = swarm:install
