[allocate]
source = [
  . $scripts/iaas/all.sh,
  . $scripts/random/random.sh
]
spawn = pty
exec = [
  require_args iaascfg, # pass `cbprefix' or `cbuser' to alter default node prefix or user
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read region specs distro passwd <<< $(unpack \$iaas_${iaascfg}_{region,specs,distro,password})',
  'node_label=${cbprefix-$node_prefix}-${cbuser-$admin_name}-$(random_short_token)',
  '${provider}_node_create $passwd $node_label $region $specs $distro',
  'echo Allocated node: $node_label',
  export node_label
]

[install]
source = [
  . $scripts/iaas/all.sh,
  . $scripts/ssh/ssh.sh,
  . $scripts/swarm/swarm.sh
]
spawn = pty
user = root # for ssh-copy-id to find identity file.
exec = [
  require_args iaascfg node_label, # pass typeIP=private for private connection
  # unpack parameters
  'provider=`echo $iaascfg | cut -d "_" -f 1`',
  'read passwd port <<< $(unpack \$iaas_${iaascfg}_{password,ssh_port})',
  'read docker_mirror <<< $(unpack \$iaas_${provider}_docker_mirror)',
  # get node ID and IP
  'nodeID=`${provider}_node_filter_by_label $node_label`',
  'nodeIP=`${provider}_node_map_ipaddr $nodeID ${typeIP-public}`',
  # refresh local known host list
  ssh-keygen -R $nodeIP,
  # allow ssh login from this host to new remote peer
  'set -x',
  '$scripts/ssh/ssh-copy-id.expect root@$nodeIP $passwd',
  'set +x',
  # change remote sshd port
  sshd_change_port root@$nodeIP 22 $port,
  # install docker engine
  'swarm_install root@$nodeIP $port $iaascfg $docker_mirror ${node_label}-host',
  # export node IP address
  export nodeIP
]
dep = swarm:allocate

[bootstrap]
source = . $scripts/swarm/swarm.sh
exec = [
  require_args iaascfg nodeIP,
  # unpack parameters
  'read port <<< $(unpack \$iaas_${iaascfg}_ssh_port)',

  # initialize docker warm for the first time
  $SSH -p $port root@$nodeIP $DOCKER swarm init,

  # set label for this root swarm manager
  'swarmNode=$(ssh_exec_local_cmd root@$nodeIP $port  swarm_node_id)',
  'ssh_exec_local_cmd root@$nodeIP $port  swarm_node_label $swarmNode iaascfg=$iaascfg',
  'ssh_exec_local_cmd root@$nodeIP $port  swarm_node_label $swarmNode shard=1',

  # move bootstrap config to specified place on remote host
  'src=$_config_file_'
  'dst=$(eval echo $(eval echo \$service_${service_bootstrap_service}_config_source_0))'
  'echo "scp $src => root@$nodeIP:$dst"',
  $SCP -P $port $src root@$nodeIP:$dst,

  # setup the first service
  ssh_exec_local_cmd root@$nodeIP $port  swarm_service_create $service_bootstrap_service,
  $SSH -p $port root@$nodeIP rm -f $dst,

  # finally, print node IP
  'echo Bootstrap finished, now try:',
  'echo "`tput bold;tput setaf 7` node cli.js http://$nodeIP -j swarm:list-nodes `tput sgr0`"'
  'echo View log from the first task:',
  'echo "`tput bold;tput setaf 7` node cli.js http://$nodeIP --task-log 1 `tput sgr0`"'
]
dep = swarm:install

[expand]
source = . $scripts/swarm/swarm.sh
exec = [
  require_args iaascfg nodeIP, # pass `shard=n' for naming shard, `role=manager' for role assignment
  # unpack parameters
  'read port <<< $(unpack \$iaas_${iaascfg}_ssh_port)',
  # join the swarm
  'joinCommand=`$DOCKER swarm join-token ${role-worker} | grep token`',
  $SSH -p $port root@$nodeIP $joinCommand,
  # set label for this new swarm node
  'swarmNodeID=`swarm_node_id root@$nodeIP $port`',
  'swarm_node_label $swarmNodeID iaascfg=$iaascfg',
  'swarm_node_label $swarmNodeID shard=${shard-1}',
]
dep = swarm:install

[list-nodes]
source = . $scripts/swarm/swarm.sh
if = is_swarm_manager
exec = swarm_print_nodes

[list-services]
source = . $scripts/swarm/swarm.sh
if = is_swarm_manager
exec = swarm_print_services

[service-update]
source = . $scripts/swarm/swarm.sh
exec = [
  require_args service, # pass `tag=v123' for update version
  swarm_service_update $service $tag
]
