[source]
verbose = false
source = . $scripts/iaas/ucloud.sh $ucloud_pubkey $ucloud_prikey $ucloud_username $ucloud_password $ucloud_docker_mirror

[list-nodes]
spawn = pty
exec = ucloud_node_list
dep = ucloud:source

[delete-node]
spawn = pty
exec = [
  check_args nodeid
  ucloud_node_delete $nodeid
]
dep = ucloud:source

[account-balance]
spawn = pty
exec = ucloud_account_balance
dep = ucloud:source
