[source]
verbose = false
source = . $scripts/iaas/all.sh

[list-nodes]
spawn = pty
exec = ucloud_node_list
dep = ucloud:source

[list-nodes-in-json]
spawn = pty
exec = ucloud_node_list_in_json
dep = ucloud:source

[delete-node]
spawn = pty
exec = [
  require_args nodeid,
  ucloud_node_delete $nodeid
]
dep = ucloud:source

[account-balance]
spawn = pty
exec = ucloud_account_balance
dep = ucloud:source
