[source]
verbose = false
source = . $scripts/iaas/ucloud.sh $ucloud_pubkey $ucloud_prikey

[list-nodes]
spawn = pty
exec = ucloud_node_list
dep = ucloud:source

[delete-node]
spawn = pty
exec = ucloud_node_delete $nodeid
dep = ucloud:source

[account-balance]
spawn = pty
exec = ucloud_account_balance
dep = ucloud:source
