[source]
verbose = false
source = . $scripts/iaas/all.sh

[list-nodes]
spawn = pty
exec = [
  'format=${format-table}',
  '[ $format == table ] && ucloud_node_list || ucloud_node_list_in_json'
]
dep = ucloud:source

[delete-node]
spawn = pty
exec = [
  require_args nodeid,
  ucloud_node_delete $nodeid
]
dep = ucloud:source

[account-balance]
spawn = pty
exec = ucloud_account_balance
dep = ucloud:source
