{
 "title": "Hardware Resources",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU iowait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu{mode=\"iowait\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Idle time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_cpu{mode=\"idle\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable / node_memory_MemTotal",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - node_memory_SwapFree / node_memory_SwapTotal",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_ms[1m]))",
     "legendFormat": "Read Time"
    },
    {
     "expr": "sum(rate(node_disk_read_time_ms[1m]))",
     "legendFormat": "Write Time"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[1m]))",
     "legendFormat": "Write Bytes"
    },
    {
     "expr": "sum(rate(node_disk_bytes_read[1m]))",
     "legendFormat": "Read Bytes"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_avail{device=\"/dev/vda1\"} / node_filesystem_size{device=\"/dev/vda1\"}",
     "legendFormat": "{{instance}} {{device}} "
    }
   ]
  }
 ]
}