{
 "title": "Calabash Gateway",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "connections", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Docker Swarm",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "swarm_nodes", "legendFormat": "Nodes" },
    { "expr": "swarm_services", "legendFormat": "Services" },
    {
     "expr": "up{job=\"gateway_monitor\"}",
     "legendFormat": "Gateway Uptime"
    }
   ]
  },
  {
   "title": "Visit and Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Visits" }
   ],
   "targets": [
    { "expr": "avg(rate(response_bytes[1m]))", "legendFormat": "Response bytes" },
    { "expr": "avg(rate(request_uri[1m]))", "legendFormat": "Request URIs" }
   ]
  },
  {
   "title": "Top Visitors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(5, increase(request_geoip[10m]))",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Response Traffic (MiB)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(5, avg_over_time(response_bytes[20s])) / (1024 * 1024)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Timecost (millisecond)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(8, avg_over_time(request_timecost[3m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Top URI Visits",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Visits in one minute" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg_over_time(request_uri{uri!=\"/metrics\",uri!=\"/services\",uri!=\"/nodes\",uri!~\"/grafana/.*\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Failed URIs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(8, rate(request_uri{status!=\"200\"}[1m]))",
     "legendFormat": "{{status}} {{uri}}"
    }
   ]
  }
 ]
}